# Generated by Django 6.0.3 on 2026-04-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='leader',
            field=models.CharField(default='TBD', max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='specialization',
            field=models.TextField(blank=True, help_text='What this department focuses on'),
        ),
    ]
