# Generated by Django 6.0.3 on 2026-04-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_app', '0002_department_leader_department_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='specialization',
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, help_text='Department specialization'),
        ),
    ]
